#pragma once

#define LRTP_MAX_PACKET 255
#define LRTP_TX_BUFFER_SZ 4
#define LRTP_RX_BUFFER_SZ 1
#define LRTP_GLOBAL_RX_BUFFER_SZ 1
#define LRTP_HEADER_SZ 8
#define LRTP_MAX_PAYLOAD_SZ (LRTP_MAX_PACKET - LRTP_HEADER_SZ)
